### ISSUE TITLE
Error on execute the script

### ISSUE THREAD

**Issue by 7he7hing** [TahaT80/Bypass-Cloud-Flare#1]
Encounter this issue -

> Traceback (most recent call last):
>   File "Bypass-Cloud-Flare.py", line 30, in __start__
>     bypass = socket.gethostbyname(str(hosts))
> socket.gaierror: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "Bypass-Cloud-Flare.py", line 49, in <module>
>     __start__()
>   File "Bypass-Cloud-Flare.py", line 34, in __start__
>     print (Fore.RED+" [!] NOT FIND " + str(bypass) + ' | ' + str(hosts))
> UnboundLocalError: local variable 'bypass' referenced before assignment

**Comment by omnituensaeternum** [comment]
same
